### ISSUE TITLE
调整代码字体大小

### ISSUE THREAD

**Issue by looker53** [doocs/md#117]
请问如何在定制 css 时调整代码字体大小，没有提供相关示例。 在公众号中如果代码字体太大，看起来不方便。

**Comment by yanglbme** [comment]
目前不支持，我们调整一下

**Comment by yanglbme** [comment]
@looker53 

已支持代码块样式自定义调整，使用示例：

```css
/* 有序列表样式 */
ol {
}
/* 无序列表样式 */
ul {
}
/* 列表项样式 */
li {
}
/* 代码块样式 */
code {
  font-size: 10px;
}
```
