### ISSUE TITLE
自定义样式中设置字体无效

### ISSUE THREAD

**Issue by Yeijon** [doocs/md#279]
很感谢大佬开发的这款排版工具！
我在使用当中希望自定义行内代码字体为`Consolas`，但是设置后没有效果，求指教

![image](https://github.com/doocs/md/assets/104615539/92523db4-0557-459a-9ef2-02d050bbffbc)

**Comment by YangFong** [comment]
1. 语法错误，`font` 不能只填一个字体，还需要补充其他参数。此处推荐修改为 `font-family`。
2. 对于自定义字体，需要导入对应的资源才可生效。

**Comment by Yeijon** [comment]
> 1. 语法错误，`font` 不能只填一个字体，还需要补充其他参数。此处推荐修改为 `font-family`。
> 2. 对于自定义字体，需要导入对应的资源才可生效。

感谢回复！
我尝试修改为
```css
/* 行内代码样式 */
codespan {
  font-family: Roboto, monospace;
}
```
但是仍旧没有效果，可能是没有对应资源？我在这方面是个小白，请教如何导入对应字体

**Comment by YangFong** [comment]
> > 1. 语法错误，`font` 不能只填一个字体，还需要补充其他参数。此处推荐修改为 `font-family`。
> > 2. 对于自定义字体，需要导入对应的资源才可生效。
> 
> 感谢回复！ 我尝试修改为
> 
> ```css
> /* 行内代码样式 */
> codespan {
>   font-family: Roboto, monospace;
> }
> ```
> 
> 但是仍旧没有效果，可能是没有对应资源？我在这方面是个小白，请教如何导入对应字体

你可以先试试加入下面这段代码：

```css
@font-face {
  font-family: "Bitstream Vera Serif Bold";
  src: url("https://mdn.github.io/css-examples/web-fonts/VeraSeBd.ttf");
}

h1 { 
 font-family: 'Bitstream Vera Serif Bold', serif; 
}
```

使用参考：

- https://developer.mozilla.org/zh-CN/docs/Web/CSS/@font-face
