### ISSUE TITLE
添加css时网页卡死

### ISSUE THREAD

**Issue by littlesulley** [doocs/md#7]
作者你好~ 我发现在添加CSS样式的时候页面会卡死（Chrome&Edge），在现有的CSS上编辑没有问题。比如在末尾添加：
```css
div {
  margin-top: 10em;
}
```
而且，复制粘贴没有问题，直接输入就会卡死。
